### ISSUE TITLE
MOM6 vgrid support

### ISSUE THREAD

**Issue by aekiss** [COSIMA/domain-tools#33]
These tools currently assume a MOM5 vgrid is used, which has 2n+1 values for an n-level grid. They therefore produce incorrect results if a MOM6 vgrid with n+1 levels is used.

Perhaps an option should be provided to use MOM6 vertical grids?

**Comment by micaeljtoliveira** [comment]
@aekiss Could you briefly explain the differences between the MOM5 and MOM6 vertical grids?

**Comment by aekiss** [comment]
MOM5 `ocean_vgrid.nc` (e.g. `/g/data/vk83/experiments/inputs/access-om2/ocean/grids/vertical/global.1deg/2020.10.22/ocean_vgrid.nc`) is a supergrid, with 2n+1 interleaved cell boundaries and centres.

MOM6 `ocean_vgrid.nc` (e.g. `/g/data/vk83/experiments/inputs/access-om3/mom/grids/vertical/global.1deg/2023.07.28/ocean_vgrid.nc`) has only n+1 cell boundaries and is missing cell centres.

**Comment by micaeljtoliveira** [comment]
@aekiss I've got a PR that adds support for MOM6 vertical grids here: #35
