### ISSUE TITLE
Optionally support C-grid connectivity in deseas

### ISSUE THREAD

**Issue by aekiss** [COSIMA/domain-tools#37]
Hi @micaeljtoliveira, does `deseas` assume B-grid connectivity requirements? I guess this is controlled by the choke criteria in   `topography_number_seas`? https://github.com/COSIMA/domain-tools/blob/master/src/topography.f90#L225

i.e. will we need to change this to allow marginal seas to be regarded as connected to the ocean when the outlet is 1 cell wide on a C-grid (e.g. Gibraltar)?

**Comment by micaeljtoliveira** [comment]
@aekiss Yes, my understanding is that it does assume B-grid connectivity.

I don't remember anymore all the details of the algorithm, but I think this is the relevant piece of code: https://github.com/COSIMA/domain-tools/blob/ab469dfcdb038633f46f6f17ed84a2efb8aa46e1/src/topography.f90#L323-L331

**Comment by aekiss** [comment]
ok, ta, as suspected then.

**Comment by aekiss** [comment]
@micaeljtoliveira it looks to me like we could optionally support C-grid connectivity rules by simply omitting the `mask` argument to `minval` here (and also in the duplicate code for the backward sweep, lines 365-6) - does that sound right? https://github.com/COSIMA/domain-tools/blob/ab469dfcdb038633f46f6f17ed84a2efb8aa46e1/src/topography.f90#L328-L329

**Comment by micaeljtoliveira** [comment]
@aekiss Yes, that sounds right.

**Comment by aekiss** [comment]
Just for reference, mom6-regional has this code for removing narrow channels https://github.com/COSIMA/regional-mom6/blob/0bfe4ba7aab3f27821476b83130861d6922a6c80/regional_mom6/regional_mom6.py#L1311

**Comment by aekiss** [comment]
@micaeljtoliveira, @angus-g do you know whether `topography_nonadvective` is necessary for MOM6? We don't want to do `coastal`, but is `potholes` worthwhile on a z* vertical grid (using different criteria to suit a C grid)? I guess I'm asking, does anything bad happen if a cell is surrounded on all sides by vanishing layers? (I'm guessing it's fine)

https://github.com/COSIMA/domain-tools/blob/ab469dfcdb038633f46f6f17ed84a2efb8aa46e1/src/topography.f90#L495

**Comment by angus-g** [comment]
> I guess I'm asking, does anything bad happen if a cell is surrounded on all sides by vanishing layers? (I'm guessing it's fine)

As long as it's wet on all those sides, I don't think there's an issue, no.
