### ISSUE TITLE
Chunksizes too small

### ISSUE THREAD

**Issue by anton-seaice** [COSIMA/domain-tools#44]
When generating the topography and mask files, domain-tools sets the chunksizes of the netcdf output as 

`chunksizes=[this%nxt/10, this%nyt/10]`

these are far too small, e.g. for a 2d 0.25 degree variable, the whole variable will be a couple of megabytes and shouldn't be split into chunks. Using the default  (i.e. no chunking) chunk sizes for these variables will be faster I think.

Lines impacted:

https://github.com/COSIMA/domain-tools/blob/94aa3e7d2f4eb73db1557dd11cb769222f333014/src/topography.f90#L166

https://github.com/COSIMA/domain-tools/blob/94aa3e7d2f4eb73db1557dd11cb769222f333014/src/topography.f90#L184

+several more in the topography.f90 file.

**Comment by micaeljtoliveira** [comment]
Probably the best would be to let users set these values from the command line. What do you think?

**Comment by anton-seaice** [comment]
I don't 'think' there is a case the users needs to set them ? The netcdf default chunksize is 4MB, which is ok as it fits easily in the nornam netCDF-4 cache.

The models only read the topo/mask files etc once, so it doesn't seem worth the effort of trying to align the chunksizes to any processor decomposition etc.

**Comment by micaeljtoliveira** [comment]
So we just use the default chunksize?

**Comment by anton-seaice** [comment]
Yep :) - we can just remove the chunksize argument from the subroutine calls.
